### ISSUE TITLE
Create Milestone 1 Report

### ISSUE THREAD

**Issue by betty-gures** [betty-gures/SWE573-Spring22#24]
Your milestone report must include at least the following items:

- [x] 1. Executive Summary: Summary of project status and any changes that are planned for
moving forward.
- [x] 2. List and status of deliverables.
- [x] 3. Evaluation of the status of deliverables and its impact on your project plan.
- [x] 4. Evaluation of tools and processes that you have used to manage your team project.
- [x] 5. A summary of work done by each team member (in tabular format)
- [x] 6. Deliverables (a) Scenarios and Mockups
- [x] 6. Deliverables (b) Software Requirements Specification
- [x] 6. Deliverables (c) Software design documents in UML
- [x] 6. Deliverables (d) Project plan
- [x] 6. Deliverables (e) Your GitHub wiki pages must be up to date with all relevant information

**Comment by betty-gures** [comment]
All requirements of the Milestone 1 were accomplished and submitted.
